services:
  # Backend API Service
  - type: web
    name: poultrymart
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromDatabase:
          name: poultrymart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dzeub4jji
      - key: CLOUDINARY_API_KEY
        value: 283288589219278
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Client Service
  - type: static
    name: poultrymart-client
    buildCommand: cd client && npm install && npm run build
    publishPath: client/dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://poultrymart.onrender.com
      - key: VITE_SOCKET_URL
        value: https://poultrymart.onrender.com
      - key: VITE_PAYPAL_CLIENT_ID
        value: AYkrBEqm9dM5MUBk32oRp5T67oVJqi3m4CrtCkLTdvfDJ135RFSy0wC2M8Mb7wlIWXndWc9KiLOTITyT
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database configuration
databases:
  - name: poultrymart-db
    plan: free
    ipAllowList: []
