services:
  # Combined frontend and backend service
  - type: web
    name: poultrymart
    runtime: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: cd server && node server.js
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        fromDatabase:
          name: poultrymart-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dzeub4jji
      - key: CLOUDINARY_API_KEY
        value: 283288589219278
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://poultrymart-web.onrender.com
      - key: VITE_API_URL
        value: https://poultrymart.onrender.com
      - key: VITE_SOCKET_URL
        value: https://poultrymart.onrender.com
      - key: VITE_PAYPAL_CLIENT_ID
        value: AYkrBEqm9dM5MUBk32oRp5T67oVJqi3m4CrtCkLTdvfDJ135RFSy0wC2M8Mb7wlIWXndWc9KiLOTITyT
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - source: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-Content-Type-Options
            value: nosniff
          - key: Referrer-Policy
            value: strict-origin-when-cross-origin

databases:
  - name: poultrymart-db
    plan: free
    ipAllowList: []
