services:
  # Backend API service
  - type: web
    name: poultrymart-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend static site
  - type: web
    name: poultrymart-client
    env: static
    buildCommand: |
      # Use Node.js version from .nvmrc
      export NODE_VERSION=$(cat .nvmrc)
      nvm use $NODE_VERSION
      # Install client dependencies with dev dependencies
      cd client && npm ci --include=dev
      # Build the project with production environment
      NODE_ENV=production npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_API_URL
        value: https://api.chickenpoultry.shop
      - key: VITE_SOCKET_URL
        value: https://api.chickenpoultry.shop
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.14.0
