services:
  - type: web
    name: poultrymart-server
    env: node
    buildCommand: npm run build:server
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true

  - type: web
    name: poultrymart-client
    env: node
    buildCommand: npm run build:client
    startCommand: cd client && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: poultrymart-server
          type: web
          property: url
    autoDeploy: true
